### ISSUE TITLE
SLAM datasets

### ISSUE THREAD

**Issue by liliang2655** [Chenxy875/URRE-Net#1]
大佬您好，拜读过您的论文后，对您论文中提到的自制实际工程环境的SLAM数据集很感兴趣，您论文里说到通过AprilTags获得GT，想请问您，这些数据集您开源吗？您之前是否考虑过其他公开的弱光SLAM数据集？

最后感谢您的工作！同时期待您的回复！

**Comment by Chenxy875** [comment]
Hello, our data set will be released after our next task is completed (being processed)
If you're interested in these architectural scene datasets, check out Conslam: Construction data set for slam.
Thank you for your interesting. You're welcome to reference our work.

**Comment by liliang2655** [comment]
> Hello, our data set will be released after our next task is completed (being processed) If you're interested in these architectural scene datasets, check out Conslam: Construction data set for slam. Thank you for your interesting. You're welcome to reference our work.

thank you for your reply. In fact, I am a SLAM beginner and currently want to do low-light SLAM, but I have not found a more suitable and standard low-light SLAM data set. I wonder if you have any recommended public data sets. Again looking forward to your reply.

**Comment by Chenxy875** [comment]
In fact, there are no really publicly available large-scale V-SLAM low-light datasets. 
 Conslam: Construction data set for slam.  There are also many low-light scenes and the quality is very good, you can try.
We will upload our data set as soon as possible
