### ISSUE TITLE
Request for Integration Details of Image Enhancement with SLAM

### ISSUE THREAD

**Issue by liliang2655** [Chenxy875/URRE-Net#3]
I hope this message finds you well. I have been exploring your project and found the code for the image enhancement network very insightful. I read your paper on the integration of image enhancement with SLAM, and I am very interested in understanding how you achieved this integration.

I noticed that the current repository provides the code for the image enhancement network, but the details on how it is integrated with SLAM are not included. I would like to ask if you could kindly share some details or the code related to the integration method.

I believe this information would be very beneficial for my research. If you are willing to share, I would greatly appreciate any guidance or resources you can provide.

Thank you very much for your time and consideration. I look forward to your response.

**Comment by Chenxy875** [comment]
I placed the low-light image enhancement code before v-slam, without tight integration. It is part of the entire slam system (pre-processing module). You can use processing module in your ros space before V-SLAM.

**Comment by liliang2655** [comment]
> I placed the low-light image enhancement code before v-slam, without tight integration. It is part of the entire slam system (pre-processing module). You can use processing module in your ros space before V-SLAM.




Thank you for your previous response regarding the integration of the image enhancement module with V-SLAM. I am currently facing some challenges related to the real-time performance of the integrated system.

Specifically, I have noticed that the image enhancement process can be quite time-consuming, which reduces the overall frame rate of the SLAM system to less than 10 frames per second. During the review of my paper's first draft, one of the reviewers raised a concern about the real-time performance of the SLAM system.

I wanted to ask if you have encountered similar feedback from reviewers regarding real-time performance in your own work. If so, could you please share how you addressed such concerns in your responses?

I would greatly appreciate any insights or suggestions you could provide on this matter. Thank you again for your time and assistance.

**Comment by Chenxy875** [comment]
Good question.   My enhanced model uses a laptop GPU and can reach over 100 fps.   It can also achieve 30 fps or more when used with SLAM.   Since the camera operates at a frequency of 30, it can run in real time.
I’m not sure what size model you are using;   perhaps your GPU has lower computational capability, or the model is too large.   If you can use a more powerful GPU, you might achieve better results, as current mobile robot platforms have strong computing power.   You could provide details about the model size or computational power you are using.
Perhaps you can also simplify the model,  like dec--> dce++
Generally speaking, real-time operation is good.   I hope my reply is useful.   If you're interested, you can also refer to  Chen X, Yu Y. An unsupervised low-light image enhancement method for improving V-SLAM localization in uneven low-light construction sites[J].  Automation in Construction, 2024, 162: 105404.  (welcome for citing)

**Comment by liliang2655** [comment]
> Good question. My enhanced model uses a laptop GPU and can reach over 100 fps. It can also achieve 30 fps or more when used with SLAM. Since the camera operates at a frequency of 30, it can run in real time. I’m not sure what size model you are using; perhaps your GPU has lower computational capability, or the model is too large. If you can use a more powerful GPU, you might achieve better results, as current mobile robot platforms have strong computing power. You could provide details about the model size or computational power you are using. Perhaps you can also simplify the model, like dec--> dce++ Generally speaking, real-time operation is good. I hope my reply is useful. If you're interested, you can also refer to Chen X, Yu Y. An unsupervised low-light image enhancement method for improving V-SLAM localization in uneven low-light construction sites[J]. Automation in Construction, 2024, 162: 105404. (welcome for citing)

Thank you for your detailed response and the suggestions. I wanted to clarify that my image enhancement algorithm is also based on an existing model, with some improvements. However, the processing time for the enhancement alone is around 100 ms per frame, which has been challenging to reduce further.

I also wanted to let you know that I have cited your paper in my own work and used URRE-Net as one of the comparative models in my experiments. 

Given the constraints I’m facing with processing time, I will explore your suggestions regarding model simplification or potential hardware upgrades. If you have any further advice on optimizing the enhancement process or alternative approaches, I would greatly appreciate it.

Thank you once again for your help!
